esphome:
  name: upstairs-climate-receiver
  project:
    name: "custom.nrf24_attiny_gateway"
    version: "1.0"
  libraries:
    - SPI
    - nrf24/RF24@1.4.9

esp8266:
  board: nodemcuv2

external_components:
  - source:
      type: git
      url: https://github.com/axelfurlan/hassio_stuff.git
      ref: master
    refresh: 0d
    components: [ esp_nrf24l01_receiver ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "UpstairsClimateReceiver"
    password: "PaperoDonald!"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0j+AjlcjCAWQDTnR7MVQFCk+OYEQA39xRP/UQlcf2Ek="

ota:
  - platform: esphome
    password: "5c3a7a27f915e08241196e007a45e212"

web_server:
  port: 80

time:
  - platform: homeassistant


sensor:
  - platform: esp_nrf24l01_receiver
    name: "Upstairs climate receiver"
    cs_pin: D4
    ce_pin: D2
    channel: 88
    sensors:
        sensor_0: # TEST
            temperature:
                name: "Endurance test temperature"
            humidity:
                name: "Endurance test humidity"
            last_packet_timestamp:
                name: "Endurance test last packet timestamp"
            sender_address: "1STUD"

